### ISSUE TITLE
Allow to log errors from messages again

### ISSUE THREAD

**Issue by real34** [franciscofsales/winston-sentry-log#1]
Hi!

First of all, thank you for your work on this project.

We stumble upon an error due to the recent https://github.com/franciscofsales/winston-sentry-log/commit/04acc997fe6b495c5b882d6482ad1995b35173ad change.

When logging an error (with level = `error`) that is not an `Error` object, it is logged directly as en exception in Sentry. Sentry throws a new error which then appears in the server:

> Error: Non-Error exception captured with keys: client, data, date, level, message

A solution would be to default to the legacy `new Error(message)` in case `info` is not an error. (using sentry’s `isError` utils for instance).
See https://github.com/getsentry/sentry-javascript/blob/81a34127cde1cbf97e634c3c914a22e03d46a952/packages/node/src/backend.ts#L3

Do you think it could work?

**Comment by franciscofsales** [comment]
@real34 
thanks for the kind words.
It should work, created a PR #2 for it, will merge soon

**Comment by real34** [comment]
Awesome! We will deploy it as soon as the new version is released.

**Comment by franciscofsales** [comment]
@real34 should be available as soon as the registry updates. Let me know if you still have any trouble with it, thanks

**Comment by mzanibelli** [comment]
Hi!
We successfully use your plugin in production. Thanks!
We might need to re-open that issue though, because a new unintended behavior was introduced.

When using `new Error`, it sends and error message with *the same stack trace over and over* resulting in having only *one* open Sentry issue with many different associated *events*. In other words, it logs an error that seems to originate from `captureException` when it actually is a Winston error log coming from any part of the app. Is that clear? :)

Do you think there would be a way to avoid this and generate different Sentry issues related to the content of the Winston log while keeping the correct message log level?

I can provide more info and examples if needed.

**Comment by franciscofsales** [comment]
@mzanibelli are you sending an Error? That should only happen you if send a string through the transport.

**Comment by grimurd** [comment]
When using the winston v3 errors transport the isError check on [this line](https://github.com/franciscofsales/winston-sentry-log/blob/a9b26e4a68015b268f10cc8cb9cbaa795c761c7e/src/index.ts#L112) fails because the info argument is a object that has a property stack but is not an instance of Error.

As a result it creates a new error with the same message as the error that was thrown but the stack is incorrect.

Reproduction using winston v3.2.1 and latest winston-sentry-log:
```js
const winston = require('winston');
const Sentry = require('winston-sentry-log');

const logger = winston.createLogger({
    format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.splat(),
        winston.format.errors({ stack: true }),
    )
})

logger.add(new Sentry({
    config: {
        dsn: '<somedsn>'
    }
}))

logger.error(new Error('SOME_ERROR'));
```
